services:
  shopitoon:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ORIGIN=https://shopitton.dedsecm.xyz
      - DATABASE_URL=file:/app/data/local.db
    volumes:
      - ./local.db:/app/data/local.db # Pour persister la base de données SQLite
      - ./static:/app/static # Pour persister les fichiers statiques comme les avatars
    ports:
      - '7000:3000' # Port standard pour Node.js en production
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
